-- Script para crear la tabla de regalos en Supabase

CREATE TABLE gifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  "reservedBy" TEXT DEFAULT NULL
);

-- Habilitar Realtime para esta tabla
ALTER PUBLICATION supabase_realtime ADD TABLE gifts;

-- Insertar los regalos iniciales (Opcional)
INSERT INTO gifts (name, category) VALUES 
('Cuna de Ensueño', 'Muebles'),
('Ropita de Algodón', 'Ropa'),
('Set de Baño', 'Higiene'),
('Peluche de Estrellas', 'Juguetes'),
('Monitor de Bebé', 'Tecnología'),
('Manta Tejida', 'Accesorios');
